---
mgmt_ip: 10.10.20.48
mgmt_interface: GigabitEthernet 1
netconf_port: 830
ssh_port: 22
username: cisco
password: cisco_1234!
router_id: 172.16.10.1
as_number: 100
remote_as: 200
neighbor: 192.168.100.21
ingress_rep: 172.16.50.1
interfaces:
  - interface_type: GigabitEthernet
    interface_id: 2
    description: Link 2 - Configured with Ansible
    ip_address: 192.168.100.20
    subnet_mask: 255.255.255.0



loopbacks:
  - description: Loopback for Route injection
    interface_id: Loopback10
    ip_address: 172.16.10.1
    subnet_mask: 255.255.255.0

  - description: Loopback for Route injection
    interface_id: Loopback20
    ip_address: 172.16.20.1
    subnet_mask: 255.255.255.0

  - description: Loopback for Route injection
    interface_id: Loopback30
    ip_address: 172.16.30.1
    subnet_mask: 255.255.255.0

networks:
  - description: Advertise in BGP
    network: 172.16.10.0

  - description: Advertise in BGP
    network: 172.16.20.0

  - description: Advertise in BGP
    network: 172.16.30.0

nves:
  - interface_id: nve1
    loopback: 10
    vni: 6010
    ingress_rep: 172.16.40.1
  - interface_id: nve1
    loopback: 20
    vni: 6020
    ingress_rep: 172.16.50.1
  - interface_id: nve1
    loopback: 30
    vni: 6030
    ingress_rep: 172.16.60.1

snmp:
  chassis_id: Vagrant CSR
  contact: NetDevOps Team
  location: NetDev Workstation
